{ config, pkgs, ... }:

{
  home.username = "zeta";
  home.homeDirectory = "/home/zeta";
  home.stateVersion = "25.05";
  programs.git.enable = true;
  programs.bash = {
    enable = true;
    shellAliases = {
      zeta = "echo NixOS x Hyrpland Zeta configuration";
    };
  };

  wayland.windowManager.hyprland = {
    enable = true;
    xwayland.enable = true;
    settings = {
      monitor = ",preferred,auto,1";
      exec-once = [
        "waybar"
        "mako"
        "nm-applet --indicator"
        "blueman-applet"
        "swww-daemon && swww img ~/Pictures/wallpapers/mountain.jpg"
      ];

      general = {
        gaps_in = 6;
        gaps_out = 12;
        border_size = 2;
        "col.active_border" = "0xffa6e3a1"; # Catppuccin green
        "col.inactive_border" = "0xff585b70";
      };

      decoration = {
        rounding = 8;
        blur = { enabled = true; size = 5; };
        shadow = { enabled = true; range = 10; };
      };

      input = {
        kb_layout = "us";
        follow_mouse = 1;
        touchpad.natural_scroll = true;
      };

      bind = [
        # App launching
        "SUPER, Return, exec, kitty"
        "SUPER, D, exec, rofi -show drun"
        "SUPER, B, exec, thunar"
        "SUPER, W, exec, firefox"

        # Window management
        "SUPER, Q, killactive"
        "SUPER, M, exit"
        "SUPER, F, togglefloating"
        "SUPER, SPACE, fullscreen"

        # Workspace navigation
        "SUPER, 1, workspace, 1"
        "SUPER, 2, workspace, 2"
        "SUPER, 3, workspace, 3"
        "SUPER, 4, workspace, 4"
        "SUPER, 5, workspace, 5"
        "SUPER, H, movefocus, l"
        "SUPER, L, movefocus, r"
        "SUPER, K, movefocus, u"
        "SUPER, J, movefocus, d"

        # Screenshots
        "SUPER, P, exec, grim -g \"$(slurp)\" - | wl-copy"

        # Brightness
        ", XF86MonBrightnessUp, exec, brightnessctl set +10%"
        ", XF86MonBrightnessDown, exec, brightnessctl set 10%-"

        # Audio controls
        ", XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
        ", XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
        ", XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
      ];
    };
  };

  # Waybar setup
  programs.waybar = {
    enable = true;
    style = ''
      @define-color rosewater #f4dbd6;
      @define-color flamingo #f0c6c6;
      @define-color pink #f5bde6;
      @define-color mauve #c6a0f6;
      @define-color red #ed8796;
      @define-color maroon #ee99a0;
      @define-color peach #f5a97f;
      @define-color yellow #eed49f;
      @define-color green #a6da95;
      @define-color teal #8bd5ca;
      @define-color sky #91d7e3;
      @define-color sapphire #7dc4e4;
      @define-color blue #8aadf4;
      @define-color lavender #b7bdf8;
      @define-color text #cad3f5;
      @define-color subtext1 #b8c0e0;
      @define-color subtext0 #a5adcb;
      @define-color overlay2 #939ab7;
      @define-color overlay1 #8087a2;
      @define-color overlay0 #6e738d;
      @define-color surface2 #5b6078;
      @define-color surface1 #494d64;
      @define-color surface0 #363a4f;
      @define-color base #24273a;
      @define-color mantle #1e2030;
      @define-color crust #181926;

      * {
        font-family: "JetBrainsMono Nerd Font", monospace;
        font-size: 12px;
        color: @text;
      }

      window#waybar {
        background: @base;
        border-bottom: 2px solid @mauve;
      }

      #workspaces button {
        color: @text;
        padding: 0 5px;
      }

      #workspaces button.active {
        background: @surface0;
        color: @mauve;
      }

      #clock {
        color: @peach;
      }

      #network {
        color: @sky;
      }

      #battery {
        color: @green;
      }

      #pulseaudio {
        color: @blue;
      }

      #tray {
        padding-right: 8px;
      }
    '';
    settings = {
      mainBar = {
        layer = "top";
        position = "top";
        modules-left = [ "hyprland/workspaces" ];
        modules-center = [ "clock" ];
        modules-right = [ "pulseaudio" "network" "battery" ];

        "clock" = {
          format = "{:%a %d %b %H:%M}";
          tooltip = false;
        };
        "battery" = {
          format = "{capacity}%";
          format-charging = "⚡ {capacity}%";
        };
        "network" = {
          format-wifi = " {essid}";
          format-ethernet = " {ifname}";
          format-disconnected = "⚠ Disconnected";
        };
      };
    };
  };
  programs.rofi = {
    enable = true;
    package = pkgs.rofi;

    extraConfig = {
      modi = "drun,run,window";
      show-icons = true;
      terminal = "kitty";
      font = "JetBrainsMono Nerd Font 12";
    };

    # Define theme inline (as a file generated by Nix)
    theme = builtins.toFile "catppuccin-mocha.rasi" ''
      * {
        background: #1e1e2e;
        foreground: #cdd6f4;
        border-color: #89b4fa;
        selected-background: #45475a;
        selected-foreground: #89b4fa;
        font: "JetBrainsMono Nerd Font 12";
      }

      window {
        background-color: @background;
        border: 2px;
        border-radius: 8px;
      }

      listview {
        spacing: 4;
      }

      element selected {
        background-color: @selected-background;
        foreground: @selected-foreground;
      }
    '';
  };
}
